package com.example.aakashb.howardchat;

import com.google.firebase.database.DataSnapshot;

/**
 * Created by aakashb on 8/7/17.
 */

public class Message {
    private String mUserName;
    private String mUserId;

    private String mUserMessage;
    private String mFromUserName;
    private String mFromUserId;
    private String mMessageFrom;

    public Message(String userName, String userId, String message) {
        mUserName = userName;
        mUserId = userId;
        mUserMessage = message;
        // Note we do not generate a timestamp...that's only generated by the server.
    }

    public Message(DataSnapshot pingSnapshot) {
        mFromUserName = pingSnapshot.child("fromUserName").getValue(String.class);
        mFromUserId = pingSnapshot.child("fromUserId").getValue(String.class);
        mMessageFrom = pingSnapshot.child("content").getValue(String.class);
    }

    public String getUserName() {
        return mUserName;
    }

    public String getMessage() {
        return mMessageFrom;
    }

    public String getUserId() {
        return mUserId;
    }

    public String sentUserName(){
        return mFromUserName;
    }

    public String sentUserId(){
        return mFromUserId;
    }

    public String sentContent(){
        return mMessageFrom;
    }


}
